name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
      - name: 2. Login to Docekrhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 3. Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ankisile/hostservice:${{ github.sha }}
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with:
          repository: 'ankisile/hostsvc-cd'
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: 2. Change Docker tag
        run: |
          sed -i "s/image: ankisile\/nodeapp:.*/image: ankisile\/nodeapp:${{ github.sha }}/g" hostservice-deploy.yml
          git config --global user.email "ankisile@gmail.com"
          git config --global user.name "ankisile"
          git commit -am "triggered by github action"
          git push origin "main"